'use strict';
var Chai = require('chai');
var supertest = require('supertest');
var td = require('testdouble');
var api_1 = require('../../../api/api');
var app = api_1["default"];
exports.app = app;
var request = supertest;
exports.request = request;
var expect = Chai.expect;
exports.expect = expect;
var testDouble = td;
exports.testDouble = testDouble;
